language: java
sudo: required
matrix:
  include:
    - jdk: openjdk8
      env: JAVA_RELEASE=8 JAVA_VERSION=1.8 SCALA_VERSION=2.11
    - jdk: openjdk11
      env: JAVA_RELEASE=11 JAVA_VERSION=11 SCALA_VERSION=2.12
env:
  global:
    - NO_GCE_CHECK=true
script:
  - mvn -B verify -Djava.release=$JAVA_RELEASE -Djava.version=$JAVA_VERSION -Dscala.version=$SCALA_VERSION -Ddisq.test.real.world.files.dir=$TRAVIS_BUILD_DIR/gatk/src/test/resources/large -Ddisq.test.real.world.files.ref=$TRAVIS_BUILD_DIR/gatk/src/test/resources/large/human_g1k_v37.20.21.fasta -Ddisq.samtools.bin=/usr/bin/samtools -Ddisq.bcftools.bin=/usr/bin/bcftools
cache:
  directories:
    - $HOME/.m2
before_install:
  - src/build/bin/install-samtools.sh
  - src/build/bin/install-bcftools.sh
  - src/build/bin/checkout-gatk-large-files.sh
after_success:
  - '[[ $TRAVIS_BRANCH == "master" ]] && { mvn deploy --settings src/build/travis/settings.xml -DskipTests=true -B ; };'
